spring.application.name=auth-service
server.port=8081

spring.datasource.url=${db_url}
spring.datasource.name=${db_username}
spring.datasource.password=${db_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false