spring.application.name=auth-service
server.port=8081

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

jwt.secret=my-super-secret-key-my-super-secret-key
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000

spring.thymeleaf.cache=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false